name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-self-hosted:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show message
        run: echo "Hello from self-hosted runner!"